# Les grands principes d’une démarche d’open data

## Aux origines de l’ouverture des données : retours sur quelques grandes dates fondatrices

### 2005 : Open Definition, une définition juridique des droits de l’usager du savoir ouvert

### 2007 : rencontre dite de Sebastopol, la définition des grands principes de l’open data 

### 2008 : “Raw Data Now”, l’appel du fondateur du web à l’ouverture des données brutes

### 2008 : le modèle en 5 étoiles, une échelle de l’ouverture des données

### 2010 : Open Data Index, un classement de l’ouverture des données essentielles

### 2011 : la création de l’Open Government Partnership

### 2013 : la charte internationale de l’open data, vers l’ouverture par défaut	

## Le contexte juridique en France

## Revue des grands principes de l’ouverture des données 

## Les bénéfices attendus d’une politique d’open data pour une collectivité

### Organisationnels
gain de temps dans les procédures de demandes de données, valorisation du travail des agents, dialogue avec les citoyens, nouvelles possibilités de croisement et d’exploitation des données en interne, possibilité de mutualisation des outils…

### Système d’information
amélioration de la qualité des données, cartographie du SI, soutien à l’open source et la souveraineté du SI, possibilité de partage interne pour les données non ouvrables, avancement de projets de dématérialisation…

### Communication
transparence renforcée, visualisation de données pour la communication, suivi des engagements, implication des citoyens…

### Economie
soutien aux startups, rationalisation de la politique d’achat par l’accès à de nouveaux services réutilisant les données, développement ouvert de services au public par des hackathons et des appels à projets…

## Les grands acteurs d’un projet d’open data

## En résumé, qu'est-ce qu'une donnée publique ouverte ?

une donnée
un document administratif
librement réutilisable
ouverte techniquement
brute
